# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: a17t
email: a17t@sendmiles.email
description: >- # this means to ignore newlines until "baseurl:"
  Build beautiful, unique interfaces without reinventing the wheel.
  Let a17t provide the core building blocks, then customize with ease.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://a17t.miles.land" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: MilesMcCain
github_username:  milesmcc
permalink: pretty

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Helpful variables
tones: ["neutral", "positive", "warning", "critical", "info", "urge"]
priorities: ["low", "normal", "high"]
